[www]
clear_env = no
catch_workers_output = yes
php_admin_flag[short_open_tag] = off
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /tmp/fpm-php-errors.log
access.log = /tmp/fpm-access.log